In [1]:
import pandas as pd
from interacao_abelha_planta.sankey import SankeyGraph
from interacao_abelha_planta.images import ImageGenerator

In [2]:
df = pd.read_csv(filepath_or_buffer='../data/20260709/Lucas Observação Serra do Mendanha att - Coletas Maciço.csv')

In [3]:
gen = ImageGenerator(df=df)

In [7]:
dfs = gen.split_data_into_pages(pages=3)

[(0, 7), (7, 23), (23, None)]

In [5]:
dfs[0]

                      abelha                  flor
8             Psaenythia sp.     Solanum hexandrum
10             Thygater sp.1        Ipomoea indica
11             Thygater sp.2        Ipomoea indica
12              Euglossa sp.        Ipomoea indica
13      Melitoma segmentaria        Ipomoea indica
..                       ...                   ...
172      Paratetrapedia sp.1          Solanum sp.1
173             Bombus morio          Solanum sp.1
175   Ariphanarthra palpalis     Solanum hexandrum
180  Trigonopedia ferruginea  Psychotria leiocarpa
184       Tetragona clavipes      Croton triqueter

[95 rows x 2 columns]

In [6]:
dfs[1]

                      abelha                 flor
0          Osiris variegatus   Maranta leuconeura
1                Osiris sp.2   Maranta leuconeura
2          Osiris variegatus     Maranta cristata
3                Osiris sp.3     Maranta cristata
4    Trigonopedia ferruginea     Begonia concinna
..                       ...                  ...
181         Plebeia droryana     Maranta cristata
182  Trichocerapis mirabilis         Saranthe sp.
183         Plebeia droryana         Saranthe sp.
185             Exaerete sp.        Catasetum sp.
186           Apis mellifera  Serjania caracasana

[92 rows x 2 columns]